join_server: Session Class Reference
Session Class Reference
Class Session - establishes a network connection.
#include <Session.h>
Public Member Functions
Session (tcp::socket socket, std::shared_ptr< CmdHandler > cmd_handler, Mode mode)
void start ()
Private Types
enum { max_length = 1024 }
Private Member Functions
void do_read ()
void do_write (const char *data, std::size_t length)
Private Attributes
tcp::socket _socket
char _data [max_length]
std::string _command
std::shared_ptr< CmdHandler > _cmd_handler
Mode _mode
Detailed Description
Class Session - establishes a network connection.
Parameters
socket Network socket.
sender Shared pointer to CmdHandler.
mode Server operation mode (line or symbolic).
Definition at line 24 of file Session.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
max_length
Definition at line 36 of file Session.h.
{ max_length = 1024 };
Constructor & Destructor Documentation
Session()
Session::Session (tcp::socket socket, std::shared_ptr< CmdHandler > cmd_handler, Mode mode) inline
Definition at line 26 of file Session.h.
            : _socket(std::move(socket)), _cmd_handler(std::move(cmd_handler)), _mode(mode) {}
Member Function Documentation
do_read()
void Session::do_read () private
Definition at line 7 of file Session.cpp.
                      {
    auto self(shared_from_this());
    _socket.async_read_some(boost::asio::buffer(_data, max_length),
        [this, self](boost::system::error_code ec, std::size_t length) {
            if (!ec) {
                if (_mode == Mode::Symbolic) {
                    if (_data[length - 1] != '\n') {
                        _command += std::string(_data, length);
                        do_read();
                    } else {
                        if (_command.length() > 0) {
                            std::string response {_cmd_handler->execute(_command) + std::string(NEW_LINE)};
                            _command.clear();
                            do_write(response.c_str(), response.length());
                            //do_read();//asynchronous sending of response
                        }
                    }
                } else if (_mode == Mode::Line) {
                    std::string response {_cmd_handler->execute(std::string(_data, length)) + std::string(NEW_LINE)};
                    do_write(response.c_str(), response.length());
                    //do_read();//asynchronous sending of response
                }
            }
        });
}
Referenced by do_read(), do_write(), and start().
do_write()
void Session::do_write (const char * data, std::size_t length) private
Definition at line 33 of file Session.cpp.
{
    auto self(shared_from_this());
    boost::asio::async_write(_socket, boost::asio::buffer(data, length),
        [this, self](boost::system::error_code ec, std::size_t /*length*/) {
            if (!ec) {
                do_read();//synchronous sending of response
            }
        });
}
Referenced by do_read().
start()
void Session::start ()
Definition at line 3 of file Session.cpp.
                    {
    do_read();
}
Member Data Documentation
_cmd_handler
std::shared_ptr<CmdHandler> Session::_cmd_handler private
Definition at line 40 of file Session.h.
Referenced by do_read().
_command
std::string Session::_command private
Definition at line 38 of file Session.h.
Referenced by do_read().
_data
char Session::_data[max_length] private
Definition at line 37 of file Session.h.
Referenced by do_read().
_mode
Mode Session::_mode private
Definition at line 41 of file Session.h.
Referenced by do_read().
_socket
tcp::socket Session::_socket private
Definition at line 35 of file Session.h.
Referenced by do_read(), and do_write().
The documentation for this class was generated from the following files:
Session.h
Session.cpp