join_server: CmdHandler Class Reference
CmdHandler Class Reference
Class CmdHandler - creates a database and necessary tables. Converts incoming commands into SQL-queries and returns their result.
#include <CmdHandler.h>
Public Member Functions
CmdHandler ()
std::string execute (const std::string &command)
Private Member Functions
void create_table (const std::string &name)
Static Private Member Functions
static std::vector< std::string > split (const std::string &str)
static std::string check_status (const query_result &result)
static std::string result_to_string (const query_result &result)
Private Attributes
SQL _sql
Detailed Description
Class CmdHandler - creates a database and necessary tables. Converts incoming commands into SQL-queries and returns their result.
Definition at line 16 of file CmdHandler.h.
Constructor & Destructor Documentation
CmdHandler()
CmdHandler::CmdHandler ()
Definition at line 5 of file CmdHandler.cpp.
                       {
    create_table("A");
    create_table("B");
}
Member Function Documentation
check_status()
std::string CmdHandler::check_status (const query_result & result) static private
Definition at line 64 of file CmdHandler.cpp.
{
    if (!result.empty() && result[0][0] == "ERR") {
        return "ERR " + result[0][1];
    } else {
        return "OK";
    }
}
Referenced by execute().
create_table()
void CmdHandler::create_table (const std::string & name) private
Definition at line 59 of file CmdHandler.cpp.
{
    std::string query {"CREATE TABLE " + name + "(id INTEGER PRIMARY KEY, name TEXT)"};
    _sql.execute_query(query.c_str());
}
Referenced by CmdHandler().
execute()
std::string CmdHandler::execute (const std::string & command)
Definition at line 10 of file CmdHandler.cpp.
{
    std::string query;
    std::vector<std::string> words {split(command)};
    if (words.empty()) {
        return "ERR empty command";
    }
    if (words[0] == "INSERT") {
        if (words.size() >= 4) {
            query = "INSERT INTO " + words[1] + " VALUES(" + words[2] + ", '" + words[3] + "');";
        } else {
            return "ERR incomplete command";
        }
    } else if (words[0] == "TRUNCATE") {
        if (words.size() >= 2) {
            query = "DELETE FROM " + words[1] + ";";
        } else {
            return "ERR incomplete command";
        }
    } else if (words[0] == "INTERSECTION") {
        query = "SELECT a.id, a.name, b.name FROM A AS a, B AS b WHERE a.id = b.id;";
    } else if (words[0] == "SYMMETRIC_DIFFERENCE") {
        query = "SELECT id, name, '' AS name FROM A WHERE id NOT IN (SELECT id FROM B) UNION "
                "SELECT id, '' AS name, name FROM B WHERE id NOT IN (SELECT id FROM A);";
    } else {
        return "ERR unrecognized command";
    }
    query_result result {_sql.execute_query(query.c_str())};
    std::string status {check_status(result)};
    if (status == "ERR UNIQUE constraint failed: A.id" ||
        status == "ERR UNIQUE constraint failed: B.id") {
        status = "ERR duplicate " + words[2]; //for INSERT only
    }
    return result_to_string(result) + status;
}
Referenced by TEST().
result_to_string()
std::string CmdHandler::result_to_string (const query_result & result) static private
Definition at line 72 of file CmdHandler.cpp.
{
    std::string str;
    for (auto it_row = result.cbegin() + 1; it_row < result.cend(); ++it_row) {
        for (auto it_value = it_row->cbegin(); it_value < it_row->cend(); ++it_value) {
            if (it_value != it_row->cbegin()) {
                str += ',';
            }
            str += *it_value;
        }
        str += NEW_LINE;
    }
    return str;
}
Referenced by execute().
split()
std::vector< std::string > CmdHandler::split (const std::string & str) static private
Definition at line 47 of file CmdHandler.cpp.
{
    std::vector<std::string> result;
    std::string word;
    std::stringstream ss(str);
    while (ss >> word) {
        result.push_back(word);
    }
    return result;
}
Referenced by execute().
Member Data Documentation
_sql
SQL CmdHandler::_sql private
Definition at line 28 of file CmdHandler.h.
Referenced by create_table(), and execute().
The documentation for this class was generated from the following files:
CmdHandler.h
CmdHandler.cpp